### ISSUE TITLE
Implement audio.onMetadata event on iOS

### ISSUE THREAD

**Issue by akaGelo** [2alab/audioplayer#1]
String title =  IcyInfo.title // " - " or "KHALID;SWAE LEE - The Ways"
channel.invokeMethod("audio.onMetadata", title);

**title** is **not** null and **not** empty

**Comment by akaGelo** [comment]
assert(title **!= null**)
channel.invokeMethod("audio.onMetadata", title);

**Comment by abuharsky** [comment]
fixed
